### ISSUE TITLE
MSB8029 warning

### ISSUE THREAD

**Issue by sabonerune** [sabonerune/wwopy#32]
以下の設定で抑制できるがそれをする意味はないかもしれない。

```toml
[[tool.scikit-build.overrides]]
if.platform-system = "^win32"
cmake.args = ["-noWarn:MSB8029"]
```

- ref https://scikit-build-core.readthedocs.io/en/latest/configuration/index.html#configuring-cmake-arguments-and-defines
- ref https://scikit-build-core.readthedocs.io/en/latest/configuration/overrides.html#platform-system-string
- ref https://learn.microsoft.com/visualstudio/msbuild/errors/msb8029
- ref https://learn.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference#switches
